# Generated by Django 3.2 on 2022-05-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_monthlycosts_monthlycost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlycost',
            unique_together={('month_number', 'year')},
        ),
    ]
