# Generated by Django 3.2 on 2022-05-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_monthlycost_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-bought_at']},
        ),
    ]
